export const CREATED_STATUS = 201
export const ERROR_SERVER_STATUS = 500
export const INVALID_REQUEST_STATUS = 400

export default {
  CREATED_STATUS,
  ERROR_SERVER_STATUS,
  INVALID_REQUEST_STATUS,
}
