export const HTTP_UNEXPECTED_ERROR_STATUS = 500
export const HTTP_INVALID_CREDENTIALS_STATUS = 401
export const HTTP_OK_STATUS = 200

export default {
  HTTP_UNEXPECTED_ERROR_STATUS,
  HTTP_INVALID_CREDENTIALS_STATUS,
  HTTP_OK_STATUS,
}
